name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: read

jobs:
  nightly:
    uses: ./.github/workflows/_reusable-ci.yml
    with:
      python-version: "3.11"
      run-audit: true
